---

- name: Delete virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_virtual_machine }}"
    state: absent
  ignore_errors: yes

- name: Delete network interface
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_network_interface }}"
    state: absent
  ignore_errors: yes

- name: Delete security group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_security_group }}"
    state: absent
  ignore_errors: yes

- name: Delete public ip
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_public_ip_address }}"
    state: absent
  ignore_errors: yes

- name: Delete subnet
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_subnet }}"
    virtual_network: "{{ azure_virtual_network }}"
    state: absent
  ignore_errors: yes

- name: Delete virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_virtual_network }}"
    state: absent
  ignore_errors: yes

- name: Delete storage account
  azure_rm_storageaccount:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_storage_account }}"
    state: absent
  ignore_errors: yes

- name: Delete a resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group }}"
    state: absent
    force: yes
  ignore_errors: yes
