---
- name: Create storage account
  azure_rm_storageaccount:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_storage_account }}"
    account_type: "{{ azure_storage_account_type }}"
# tags: test

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_virtual_network }}"
    address_prefixes: "10.0.0.0/24"
# clé UVCPqRmarOAzMnKj8FFbrmyOKDzryj3DGeL5FWzE9sU=

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_subnet }}"
    address_prefix: "10.10.0.0/24"
    virtual_network: "{{ azure_virtual_network }}"

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ azure_resource_group }}"
    allocation_method: Static
    name: "{{ azure_public_ip_address }}"

- name: Create security group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_security_group }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound

- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_network_interface }}"
    virtual_network: "{{ azure_virtual_network }}"
    subnet: "{{ azure_subnet }}"
    public_ip_name: "{{ azure_public_ip_address }}"
    security_group: "{{ azure_security_group }}"

- name: Create virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_virtual_machine }}"
    vm_size: Standard_D1
    storage_account: testaccount001
    storage_container: testvm001
    storage_blob: testvm001.vhd
    admin_username: admin
    admin_password: Password!
    network_interfaces: testnic001
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.4'
      version: latest
